# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b12672da654abdff70c5575c8f0b6229bddac277757d98ed5c7a300b59986c4a59fe88c4190994b91a7f32705788675a92f1447413bc6cecc4733bd87f0eda

test:
  secret_key_base: 5c4cde0222b7be58aa477d384bc613c1506c1daeb49b5a385109c4bdf6dc8765b3d6790dcc0c59c70dc16565d76eb1a69ff3b132cfeaec84c011893ca6b01e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
